--- # about conditionals
- hosts: all
  user: ansible
  become: yes
  connection: ssh

  tasks:
     - name: install apache for debian family
       command: apt-get install apache2 -y
       when: ansible_os_family == "Debian"


     - name: install apache for redhat
       command: yum install httpd -y 
       when: ansible_os_family | lower in ['redhat', 'redhat']
       ignore_errors: yes



