---
- hosts: all
  become: yes

  tasks:
     - name: install httpd s/w
       yum: 
          name: httpd
          state: installed
       when: ansible_os_family == "RedHat"


     - name: start httpd service
       service:
          name: httpd
          state: started
       when: ansible_os_family == "RedHat"


     - name: install apache2 s/w
       apt: 
            name: apache2
            state: present
       when: ansible_os_family == "Debian"


     - name: start apache2 service
       service:
          name: apache2
          state: started
       when: ansible_os_family == "Debian"



     - name: copy index.html file
       copy: 
          src: /home/ansible/index.html
          dest: /var/www/html
          owner: soudi
          mode: 0666


