---

- hosts: all
  become: yes


  tasks: 
     - name: creating multiple users
       user: name='{{item}}' state=present
       with_items:
             - tejaa
             - tejulu
             - bujjamma
             - chinnu

